version: '3'

services:
  mysql-inter-container:
    image: mysql:8
    container_name: mysql8-inter
    environment:
      MYSQL_DATABASE: review_db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: review_dev
      MYSQL_PASSWORD: review_1234
      TZ: 'Asia/Seoul'
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "33306:3306"
    restart: always
    networks:
      - inter-network

  springboot-inter-container:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-inter:3306/review_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "review_dev"
      SPRING_DATASOURCE_PASSWORD: "review_1234"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-inter-container
    networks:
      - inter-network

networks:
  inter-network: